### ISSUE TITLE
invalid csrf token

### ISSUE THREAD

**Issue by pqvindesland** [ubccr/mokey#102]
Hi 

I am using 4.6.8-5.el7.Centos.7 on a standalone instance for mokey only, the ipa server is 4.9.2-4.module+el8.4.0 installed on Rocky 8

When I start mokey with  /usr/bin/mokey --debug server I get no errors, I get to the login screen type in the password and I get the following error:
{"time":"2021-09-21T14:52:54.587855184+02:00","level":"ERROR","prefix":"echo","file":"server.go","line":"68","message":"code=403, message=invalid csrf token"}

Initially I thought it was an issue with auth_key and enc_key so I created new with export LC_CTYPE=C; cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 64 | head -n 1 for auth_key and export LC_CTYPE=C; cat /dev/urandom | tr -dc 'a-f0-9' | fold -w 32 | head -n 1 for enc_key but I am still getting that error.

I have done some googling but I am not getting any closer to a solution, has anyone seen this issue before? 

Btw I also got error "Template not found: 403.html" which explained the white page I got after login, I did a copy of 401.html to 403,html with removed the error and also showed me a proper 403 error after login, maybe it should be added to the files?

**Comment by pqvindesland** [comment]
This is the error page I am getting after logging in
![mokey error](https://user-images.githubusercontent.com/18611311/134184237-b1e8355e-2f56-4581-acdc-bf429ac6bb73.png)
.

**Comment by aebruno** [comment]
@pqvindesland Are you running mokey over https? If not, try turning on developer mode: 
```yaml
#------------------------------------------------------------------------------
# Developer mode
#------------------------------------------------------------------------------
develop: true
```

Obviously, don't run this in production.

**Comment by pqvindesland** [comment]
Many thanks, that worked, I had a suspicion that it needed a SSL, but I wanted to ask.

**Comment by aebruno** [comment]
@pqvindesland No prob. Glad you got it sorted out.
