### ISSUE TITLE
 Failed reading config file - While parsing config: yaml: line 33: did not find expected key

### ISSUE THREAD

**Issue by pqvindesland** [ubccr/mokey#104]
Hi 

I am currently running mokey in develop true while testing, but I want to add a ssl and edit  cert: "/patch/to/cft" and  key: "/path/to/key" it fails with:  Failed reading config file - While parsing config: yaml: line 33: did not find expected key 

I have also tried to change require_verify_admin: to enable admin verificaition of new account, but it's also failing with a similar error.

Setting developer: false doesn't help either.

Do you have any idea what i am doing wrong?

Regards
Per

**Comment by aebruno** [comment]
@pqvindesland Excellent! Thanks for reporting back and glad you got it sorted out.
