### ISSUE TITLE
Mokey fails to start: "Encoding_Error"

### ISSUE THREAD

**Issue by blasphemite** [ubccr/mokey#106]
`mokey --debug server` is met with: 
```
INFO[0000] Using template dir: /usr/share/mokey/templates
FATA[0133] [Root cause: Encoding_Error] Encoding_Error: AS Exchange Error: failed to process the AS_REP < Encoding_Error: failed to unmarshal KDC's reply: asn1: syntax error: sequence truncated
```

mokey.yaml
```
driver: "mysql"
dsn: "mokey:password@tcp(mysqlhost:3306)/mokey?parseTime=true"
keytab: "/etc/mokey/mokeyapp.keytab"
ktuser: "mokeyapp"
auth_key: "e99e3eb91b0ad611e7c6e6167896be37"
enc_key: "05c5046b4475bbe7a785f96856642b68"
bind: "0.0.0.0"
port: 8080
ipahost: "ipa.example.lan"
rate_limit: false
templates: /usr/share/mokey/templates
develop: true
```

I've recreated the keytab & still get the same error. Running `klist -kt /etc/mokey/mokeyapp.keytab -e` seems to run without errors:
```
Keytab name: FILE:/etc/mokey/mokeyapp.keytab
KVNO Timestamp           Principal
---- ------------------- ------------------------------------------------------
   3 10/10/2021 00:48:24 mokeyapp@EXAMPLE.LAN (aes256-cts-hmac-sha1-96)
   3 10/10/2021 00:48:24 mokeyapp@EXAMPLE.LAN (aes128-cts-hmac-sha1-96)
```

The mokeyapp user is a member of the "Mokey User Manager" role, which possesses the "User Administrators" privilege. Not sure what I'm missing -- any assistance is appreciated.

**Comment by blasphemite** [comment]
I created a new FreeIPA server to test this, and now it's working. I'm thinking that's indicative of what's causing the problem, so I'll close this issue now. I'll edit in an update if I'm able to figure out the root cause.

**Comment by aebruno** [comment]
@blasphemite Glad to hear it's working for you. Thanks for reporting back.
