### ISSUE TITLE
Run Mokey without MySQL

### ISSUE THREAD

**Issue by nikoosns** [ubccr/mokey#110]
Hello,

Is there a possibility ot run mokey without a db backend? I've been testing it recently and found that for my usecase the database needs only to be installed and accessible, while no records are processed by the application no matter if I create user tokens, insert ssh keys or change passwords.

Regards,
Niko

**Comment by aebruno** [comment]
Hi @nikoosns yes, the next version of mokey will not require a database. We're hoping to have it released soon. The next release got delayed a bit but we are targeting this summer.

**Comment by nikoosns** [comment]
Hi @aebruno, That sounds great. Thank you very much for your reply.

**Comment by aebruno** [comment]
Fixed in v0.6.0
