### ISSUE TITLE
failed to set auth types to otp

### ISSUE THREAD

**Issue by hale177** [ubccr/mokey#117]
```
level=error msg="failed to set auth types to otp" error="ipa: error 2100 - Insufficient access: Insufficient 'write' privilege to the 'ipaUserAuthType' attribute of entry 'uid=john,cn=users,cn=accounts,dc=aaa,dc=cn'." user=john
```

I looked at the solution #98，But did not solve my problem，There is a difference between the two error **msg**(
#98 msg show: failed to reset auth types to default)

**my env：**
**ipa-server**：v4.9.10 ,centos 8
**mokey-machine**:  centos 7.9.2009

**Comment by aebruno** [comment]
@hale177 What version of mokey are you running?

**Comment by hale177** [comment]
> 

mokey version ：v0.5.6

**Comment by hale177** [comment]
> @hale177 What version of mokey are you running?

mokey version ：**v0.5.6**
