### ISSUE TITLE
Disabled tokens always show up as enabled

### ISSUE THREAD

**Issue by fajo-de** [ubccr/mokey#125]
In MoKey 6.3 when disabling a token, the token remains shown as enabled. Subsequent attempts to disable the token fail (as the token is disabled already). The token status remains shown as enabled even after logout and re-login.

Log shows:

`msg="Failed to enable OTP token" err="ipa: error 4202 - no modifications to be performed"`

on repeated attempts to disable the token.

**Comment by fajo-de** [comment]
The issue is with goipa/otp.go which expects ipatokendisabled is in uppercase which actually is not the case (at least not in FreeIPA 4.10). The value should first be converted to uppercase before comparing it.

**Comment by aebruno** [comment]
Fixed in b65a0cdb01fd0d2406f31e01768fa5c5ea459746 and ubccr/goipa#13
