### ISSUE TITLE
Getting "Forbidden - CSRF token invalid"

### ISSUE THREAD

**Issue by hanej** [ubccr/mokey#13]
I looked through the code, documentation, and previous issues but haven't been able to resolve my issue.  I set both auth_key and enc_key to random 32 characters but when I log in I get the "Forbidden - CSRF token invalid" message.  There are no messages from mokey when run from the command line.  SSL is disabled as we will be proxying this through a load balancer.  Is there another place to look for debug logs?  Any idea why I would be getting this message?

```
# /usr/bin/mokey -d server
INFO[0000] Using template dir: /usr/share/mokey/templates
INFO[0000] IPA server: localhost
WARN[0000] **WARNING*** SSL/TLS not enabled. HTTP communication will not be encrypted and vulnerable to snooping.
INFO[0000] Running on http://0.0.0.0:9000
INFO[0307] Redirect URL                                  wyaf=/
```

**Comment by hanej** [comment]
I will change my tokens to another random 32 character string but this is what I have configured now.

```
#------------------------------------------------------------------------------
# Authentication key used for HMAC token signing and secure cookies
#------------------------------------------------------------------------------
auth_key: "rbAk9oAyyIF9On3TfvF8MLP2MvogYGiN"

#------------------------------------------------------------------------------
# Encryption key used for encrypting cookies
#------------------------------------------------------------------------------
enc_key: "x8yiNJPNK43azdggEgpTMdjPEu9lZf6G"
```

**Comment by aebruno** [comment]
Which version of mokey are you running?

**Comment by hanej** [comment]
The latest.  V0.0.6

**Comment by aebruno** [comment]
The CSRF cookie requires HTTPS by default. Try setting this config option in mokey.yaml:

```
develop: true
```
This disables HTTPS for CSRF.

**Comment by hanej** [comment]
I’ve tried that as well and got the same result

**Comment by hanej** [comment]
I've must have tried a different combination that didn't work before.  I just changed `develop: true` and it's working now.  Thank you for your help.

**Comment by aebruno** [comment]
@hanej No problem. Glad to hear you got it working.
