### ISSUE TITLE
Turning on OTP does not work

### ISSUE THREAD

**Issue by ProjectPatatoe** [ubccr/mokey#137]
Gui shows `Failed to enable Two-Factor authentication`
Log shows
```
level=error msg="Failed to enable Two-Factor auth" err="ipa: error 2100 - Insufficient access: Insufficient 'write' privilege to the 'objectClass' attribute of entry 'uid=myself.admin,cn=users,cn=accounts,dc=web,dc=cloud'." username=myself.admin
```
```
# mokey --version
mokey version 0.6.3
# ipa --version
VERSION: 4.10.2, API_VERSION: 2.252
```
I did do the instruction `ipa permission-mod 'System: Modify Users' --includedattrs=ipauserauthtype`
![image](https://github.com/ubccr/mokey/assets/27925441/6066dffd-0521-481e-b4dc-aac23090d97c)

A side note, I get an email sent saying that it was enabled, It should probably be sent after confirmation.

**Comment by aebruno** [comment]
This should be fixed in b65a0cdb01fd0d2406f31e01768fa5c5ea459746 and ubccr/goipa#13
