### ISSUE TITLE
Cannot reset password for admin users

### ISSUE THREAD

**Issue by vvilaplana** [ubccr/mokey#141]
I followed all the steps in "Setup and configuration" described in README.md.
When I click "Forgot password", it sends the email to the user.
Now, if it is a non-admin user, the password is reset successfully. 
However, if it's an admin user, I get the error "Insufficient access: Insufficient 'write' privilege to the 'userPassword' attribute of entry 'uid=someadminuser,cn=users,cn=accounts,dc=mydomain,dc=com'"
How can I fix this? Do I need to grant any special permission/privilege to mokeyapp user?

**Comment by vvilaplana** [comment]
I found out this is designed that way. As per bug 773759 (https://bugzilla.redhat.com/show_bug.cgi?id=773759), "Administrative Roles given the permission to change a user password should not be able to change user's passwords that are in the Administrators Group". Therefore, the only way to allow Mokey to reset an admin password is to put Mokey user in Admins group, which is not desirable for obvious security reasons.

**Comment by aebruno** [comment]
@vvilaplana Thanks for following up. Yes this makes sense, all admin password changes should be handled outside of mokey.
