### ISSUE TITLE
Problems after Active Directory Trust setup

### ISSUE THREAD

**Issue by jehudson** [ubccr/mokey#19]
I have experienced problems after running ipa trust-add --type=ad ad_domain --admin Administrator --password.

When a user tries to change password in the mokey portal: Fatal system error is displayed. 
journatlctl -u mokey shows: 

level=error msg="failed to set user password in FreeIPA" error="ipa: error 2100 - Insufficient access: Insufficient 'write' privilege to the 'ipaNTHash' attribute.

When I add ipaNTHash attribute in System: change User Password permission, then journalctl -u mokey shows

level=error msg="failed to set user password in FreeIPA" error="ipa: change password failed. Unknown status" uid=username

When I revert with a snapshot taken before ipa-trust-add, normal behaviour is restored.

Normal ipa commands worked on mokey, fatal system error only occurred in the web portal. Presumably adding trust capability to FreeIPA introduces schema changes that Mokey is not aware of?

**Comment by aebruno** [comment]
Sorry you're having troubles. I don't have any experience setting up Active Directory with FreeIPA. From the error message my guess is there is an issue with the permissions in the Role you're using with mokey. You can try added write permissions to the ipaNTHash attribute to your mokey role.
