### ISSUE TITLE
Use email for login

### ISSUE THREAD

**Issue by AltiUP** [ubccr/mokey#33]
Hello,

First of all, thank you for this nice project.

Is it possible to use email addresses for users to log in, instead of user names?

Thank you
CG

**Comment by aebruno** [comment]
No, this is a limitation of POSIX/FreeIPA. Usernames may only include letters, numbers, _, -, .  (I believe) so you can't use an email address as a username.

**Comment by shahriar52** [comment]
It can be done in a different way. You can take email address input (also check the email validity) and write a piece of code to convert the '@' symbol to '-' and pass that to freeipa as a username. You have to plug that code into several functions in server/account.go, server/auth.go, server/hydra.go and server/signup.go

For example,
```// Email to UID conversion
	uid := strings.Replace(email, "@", "-", -1)
	uid = strings.Replace(uid, "+", "_", -1)
```

**Comment by CLSII** [comment]
> 
> 
> It can be done in a different way. You can take email address input (also check the email validity) and write a piece of code to convert the '@' symbol to '-' and pass that to freeipa as a username. You have to plug that code into several functions in server/account.go, server/auth.go, server/hydra.go and server/signup.go
> 
> For example,
> 
> ```
> 	uid := strings.Replace(email, "@", "-", -1)
> 	uid = strings.Replace(uid, "+", "_", -1)
> ```

And just replace the uid by email, would that be possible?

For example:
`uid := c.FormValue("uid")
uid := c.FormValue("mail")`
