### ISSUE TITLE
Certicate issue

### ISSUE THREAD

**Issue by jproutycct** [ubccr/mokey#34]
I am getting invalid UI x509: certificate is not valid for any names, but  expected the name of ipa server

**Comment by aebruno** [comment]
This is likely due to your ipa server certificate missing a Subject Alternative Name. Should look something like this:
```
X509v3 Subject Alternative Name: 
     DNS:ipa.yourdomain.com, othername:<unsupported>, othername:<unsupported>
```

Your ipa server domain should be listed in the `DNS:ipa.yourdomain.com` above. If it's missing then that is likely the problem.
