### ISSUE TITLE
admin-initiated account setup

### ISSUE THREAD

**Issue by g5pw** [ubccr/mokey#35]
The `newacct` command was removed in the last big refactor. Would it be possible to bring it back, or to have a similar admin-initiated account setup in place?

**Comment by aebruno** [comment]
The `resetpw` and `verify-email` commands replace the `newacct` email. Is there some specific functionality you're looking for that these commands don't currently do?

**Comment by g5pw** [comment]
Yeah, mainly a welcome-email template that sends a link to a place where the user can set their password, and a separate template for the password reset.

**Comment by g5pw** [comment]
Any idea about this one? I'm willing to contribute a patch if that's desirable :)
