### ISSUE TITLE
ory/hydra code change breaks the mokey build

### ISSUE THREAD

**Issue by shahriar52** [ubccr/mokey#39]
In server/handler.go and server/hydra.go there are following imports from Github ory/hydra,
"github.com/ory/hydra/sdk/go/hydra"
and
"github.com/ory/hydra/sdk/go/hydra/swagger"

Recently ory/hydra made some code changes and above folder and go files are not there anymore. Can you please update your repo to accommodate the hydra code changes.

**Comment by aebruno** [comment]
Thanks for reporting this. We will be updating mokey to be compatible with hydra 1.0.0 now that it's a stable release. Currently mokey works with v1.0.0-beta.8.
