### ISSUE TITLE
Example of authentication and encryption keys

### ISSUE THREAD

**Issue by ian-s-mcb** [ubccr/mokey#40]
Could you give an example of what `auth_key` and `enc_key` should look like and how to generate them?

I was sure if those keys should be plaintext or the hash of some plaintext. Also, I wasn't sure how to specify bytes in a YAML file.

In Python 3.6, I can generate 16 secure random bytes by running:
```python
import secrets
print(secrets.token_bytes(16))
```
All the project README has to say about those keys is:
> auth_key: "32 or 64 bytes random key"
> enc_key: "16, 24, or 32 byte random key"

**Comment by aebruno** [comment]
These values are used to create secure cookies. For more details about how these values are used check out the docs [here](http://www.gorillatoolkit.org/pkg/securecookie#overview). `auth_key = hashKey` and `enc_key = blockKey`. 

For your python example you could also use `print(secrets.token_hex(16))` and copy the hex string to the yaml file. Another way to generate these might be to use openssl. For example, to generate the enc_key:
```
$ openssl rand -hex 16
```

**Comment by ian-s-mcb** [comment]
Thanks! That clarified everything. I suspected that the openssl command was an option. Very helpful!
