### ISSUE TITLE
go-oidc using wrong import path

### ISSUE THREAD

**Issue by ericchiang** [ubccr/mokey#45]
github.com/coreos/go-oidc has never used gopkg.in, and we may break this soon when we add a go.mod file (https://github.com/coreos/go-oidc/pull/228).

Just a heads up that you'll need to use the correct import path "github.com/coreos/go-oidc"

https://github.com/ubccr/mokey/blob/52325f5364ad875735b64364fe48714a3644e3f0/server/handler.go#L16

**Comment by aebruno** [comment]
Thanks for the heads up!
