### ISSUE TITLE
Add username to edit in mokey.yaml (README)

### ISSUE THREAD

**Issue by Quoding** [ubccr/mokey#46]
This is a suggestion to modify the README.

This section:
```$ vim /etc/mokey/mokey.yaml
dsn: "user:pass@/dbname?parseTime=true"
keytab: "/etc/mokey/keytab/mokeyapp.keytab"
auth_key: "32 or 64 bytes random key"
enc_key: "16, 24, or 32 byte random key"
[ edit to taste ]
```

should have the username to edit, since we created the `mokeyapp` user in ipa. Default is `username`, which throws an error in Kerberos saying the principal is unknown.

**Comment by gah242s** [comment]
PR #49 should address this ticket.
