### ISSUE TITLE
Error contacting FreeIPA 

### ISSUE THREAD

**Issue by Wunderharke** [ubccr/mokey#52]
Hello,

I am struggling to connect to my IPA API.

First I had https issues however I found a solution in #25 .
Now I'm getting a new error "Error contacting FreeIPA " and there is no log output at all.

I would really appreciate any help.

**Comment by kiranshila** [comment]
How did you fix this?

**Comment by Wunderharke** [comment]
Unfortunately I could not solve the problem at all.
But I have been exploring the software structure of Free IPA and learned that Keycloak is designed for the identity and access management of Free IPA and is developed by the same people (Red Hat).
With Free IPA as backbone for [Keycloak](https://github.com/keycloak/keycloak), user administration is quite simple.
Since none of the developers have answered here, and there has been no commit since mid-February, I recommend using [Keycloak](https://github.com/keycloak/keycloak) instead.

**Comment by aebruno** [comment]
> Since none of the developers have answered here, and there has been no commit since mid-February, I recommend using [Keycloak](https://github.com/keycloak/keycloak) instead.

Apologies you didn't get a timely reply. This project is in fact actively maintained and running on production systems. If you could possibly provide more details of your setup and error your getting that would help us debug the issue your seeing. 

@kiranshila Feel free to open a new issue and we'll be happy to try and help debug.
