### ISSUE TITLE
Feature request: Add security-related headers/cookie attributes

### ISSUE THREAD

**Issue by arcuses** [ubccr/mokey#55]
Thanks for the software. Hoping you can help with adding some security-related headers to the server responses.

The following headers in particular:

* X-Frame-Options: DENY
  * As per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options), "Sites can use this to avoid click-jacking attacks, by ensuring that their content is not embedded into other sites."
* Cache-Control: no-store
  * Prevents caching of pages (e.g. ones that require authentication)
* Pragma: no-cache
  * HTTP 1.0 version of Cache-Control (HTTP 1.1)

Regarding cookies, the `httpOnly` attribute could be added to the `mokey-sessck` cookie. This prevents JavaScript from reading the cookie.

**Comment by aebruno** [comment]
@arcuses Thanks for submitting this. Will take a look and get these added.

**Comment by aebruno** [comment]
@arcuses If you get a chance, please review #59
