### ISSUE TITLE
Error: FATA[0000] encoding/hex: invalid byte: U+0068 'h'

### ISSUE THREAD

**Issue by mhaluska** [ubccr/mokey#62]
**Info:**
- OS: CentOS Linux release 8.3.2011
- Go: golang-1.14.7-2.module_el8.3.0+471+76db7791.x86_64
- Mokey: v0.5.4
- Mokey templates: v0.5.4 default

**Problem:** Mokey start fatal error
**Error:**
```
# sudo -u mokey /usr/bin/mokey --debug server
INFO[0000] Using template dir: /usr/share/mokey/templates
FATA[0000] encoding/hex: invalid byte: U+0068 'h'
```

**Comment by aebruno** [comment]
Looks like you need to adjust the `enc_key` setting in `mokey.yaml`. Try setting this to the output of:

```
$ openssl rand -hex 16
```

**Comment by mhaluska** [comment]
> Looks like you need to adjust the `enc_key` setting in `mokey.yaml`. Try setting this to the output of:
> 
> ```
> $ openssl rand -hex 16
> ```

Thank you, this solved my issue.
