### ISSUE TITLE
I cannot login in web GUI & what about auth_key & enc_key?

### ISSUE THREAD

**Issue by ckc** [ubccr/mokey#64]
As title mentioned,
may I know where these two key used? I cannot login my FreeIPA account on web GUI, possible related with it?
Currently, I just typed random key for these two separately; I am not sure where I need to match? such as where I need to put into FreeIPA?

auth_key: "32 or 64 bytes random key"
enc_key: "16, 24, or 32 byte random key"

Thanks

**Comment by zem** [comment]
Hmmm, it also looks that the manual is missing out to tell about the format of those keys as I get an error message like 

```
FATA[0000] encoding/hex: invalid byte: U+006D 'm'
```

during Startup and i think it is related to those keys.

**Comment by tim-skillcafe** [comment]
To generate 32-bit keys keys run:    openssl rand -hex 32
