### ISSUE TITLE
I'm using a server cert and get

### ISSUE THREAD

**Issue by rudgab** [ubccr/mokey#67]
level=error msg="Failed login attempt" ipa_client_error="Post \"https://localhost/ipa/session/login_password\": x509: certificate is valid for ipamaster.example.com

What is going on.

mokey from mokey-0.5.4-1.el7.x86_64

Regards, 

Rudi G.

**Comment by rudgab** [comment]
I somehow missed #25 
the normal ipa-server-setup does not give you a server line in /etc/ipa/default.conf

Sorry for the duplicate question

**Comment by aebruno** [comment]
@rudgab Glad you got it sorted out! Just to note, we now parse the IPA server from the `xmlrpc_uri` config key in `/etc/ipa/default.conf`. See ubccr/goipa#7

**Comment by rudgab** [comment]
You should know, that this git item repo isn’t within a google search reachable. Also typically only open cases are show in github. So it was only by accident that i changed to all cases and searched through these cases to get an information crucial for the installation and run of a software which is not set by default.

Maybe you add this to the installation items.

Regards,
R.G.

Von meinem iPhone gesendet

**Comment by aebruno** [comment]
@rudgab Thanks for the feedback. We do need to work on better documentation for mokey and will hopefully have some in the near future.
