### ISSUE TITLE
FreeIPA to OpenID fields mapping

### ISSUE THREAD

**Issue by jvinolas** [ubccr/mokey#68]
Hi,

According to https://openid.net/specs/openid-connect-basic-1_0.html#Scopes the profile should provide name, family_name fields but instead we see from client app this fields: ["first"]=> string(4) "John" ["last"]=> string(3) "Doe".

As the client apps expects name and family_name fields I'm wondering if it's mokey that it is not translating them correctly from freeipa to openid standard or hydra, but we see that hydra uses those fieldnames also (https://www.ory.sh/hydra/docs/reference/api/#openid-connect-userinfo).

Is this a missing field translation in mokey to openid standard?

Thanks

**Comment by aebruno** [comment]
mokey currently maps the FreeIPA field `givenname` to the `first` field in the ID Token and maps the FreeIPA field `sn` to the `last` field in the ID token.

**Comment by jvinolas** [comment]
If I'm not wrong, the freeipa user profile is this one:
![imatge](https://user-images.githubusercontent.com/2132863/108854577-57277c00-75e8-11eb-867a-83ac3b963d57.png)
And this is the OpenID standard:
![openid_profile](https://user-images.githubusercontent.com/2132863/108854732-79b99500-75e8-11eb-8e6c-e65faf12ff2e.jpg)

We connected moodle and nextcloud with hydra and mokey and we see non-standard fields on response:
["first"]=> string(4) 
["last"]=> string(3)

when those fields should be given_name and family_name as stated in OpenID standard. Is this correct?

**Comment by jvinolas** [comment]
I've done https://github.com/ubccr/mokey/pull/69 with the changes and are working with moodle and nextcloud.
