### ISSUE TITLE
Feature - Add option to always skip consent in hydra login flow

### ISSUE THREAD

**Issue by jvinolas** [ubccr/mokey#71]
As we are integrating our own apps we don't want to ask for consent to the user. Now we just forced it:

https://github.com/isard-vdi/mokey/blob/1356ffed84ce6e3830dd667e6ee8f79b1e530668/server/hydra.go#L63-L64

But it will be nice if there is an option in mokey.yml to just force no consent validation.

**Comment by jvinolas** [comment]
This PR adds this feature: https://github.com/ubccr/mokey/pull/73

**Comment by 0n1cOn3** [comment]
Hi! :) 

v0.6 removed the consent dialog. Will it be restored?"
