### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by dh-aus** [ubccr/mokey#77]
Hey Bruno,
I've noticed you've got quite a few pull requests recently, any plans to generate some new releases anytime soon?
I've got a new environment deployment coming up and I'd be happy to test a new release candidate rpm.
Thanks,
Daniel

**Comment by aebruno** [comment]
@dh-aus Yes, thanks for the reminder. I'll try and get v0.5.5 out this week.

**Comment by aebruno** [comment]
`v0.5.5` has been released.
