### ISSUE TITLE
Notification sent to user every time an authentication method is added/modified

### ISSUE THREAD

**Issue by mmorgotti** [ubccr/mokey#82]
Hi,

Do you think it would be possible to have a notification sent via email to the user every time that an authentication method is added/modified, i.e.:

- user password is reset/changed
- a new ssh key is uploaded or an existing one is removed
- a new OTP token is added or an existing one is removed/disabled/enabled

Since I understand this feature might not be needed by everyone it could be configurable via the configuration file.

Kind Regards,
Marcello

**Comment by aebruno** [comment]
@mmorgotti Great idea. I'll add it as a feature request. Thanks for the feedback
