### ISSUE TITLE
update of jquery and bootstrap shipped with mokey

### ISSUE THREAD

**Issue by mmorgotti** [ubccr/mokey#94]
Hi,

after a security scan on our instance of mokey we have found out that the jquery and bootstrap versions shipped with mokey are outdated. Is it possible to include the newest version in more recent releases?
Do you think it is possible to just replace the existing version with the newest one? Of course we are going to try it but since you have bigger insight of the project.
I had a quick look and bootstrap seems to be easier while upgrading jquery might be more challenging as migration from current version (1.11) to latest version (3.6) requires a couple of intermediate steps...

Best Regards,
Marcello

**Comment by aebruno** [comment]
@mmorgotti Thanks for reporting this. Would be great to get bootstrap/jquery updated. If you end up getting it working feel free to submit a PR. We'll try and bump this up on the priority list.

**Comment by hexa2k9** [comment]
As our Security Scanners reported the same I looked into things.

About jQuery; You can see it as a „drop-in replacement“ and everything remains working it seems. That‘s at least what I‘ve done and we’ve not seen and issues so far.

Bootstrap is a little more efforts as a significant number of CSS classes were updated, but I started to look into that. May be I‘ll find some time during holidays.

**Comment by aebruno** [comment]
@hexa2k9 Sounds great! Let us know if you get PR going. This has been on the list for a while now and would be great to get updated.

**Comment by aebruno** [comment]
fixed in v0.6.0
