### ISSUE TITLE
Provide OTP recovery codes

### ISSUE THREAD

**Issue by dsajdak** [ubccr/mokey#96]
Allow users to get backup set of OTP codes they can use in the event they lose or reset their phone

**Comment by dsajdak** [comment]
https://pagure.io/freeipa/issue/8235

**Comment by zem** [comment]
Uhm, silly question: Why aren't you creating multiple OTP tokens, one per device? 
like this: 

![image](https://user-images.githubusercontent.com/197972/128600394-500208ae-b937-4693-bf58-a542352aeb82.png)

I always thought that would be the way to go.

**Comment by aebruno** [comment]
@zem I believe this issue is in regards to creating recovery codes in the event a user lost their OTP token (changes device etc.). Currently this requires admin intervention.

**Comment by Jonathan-Caruana** [comment]
Hi,

If i may, a small but very useful enhancement could be permit ourselves to add a short description by token (like freeipa permit it)  :).

Regards,

**Comment by aebruno** [comment]
@Jonathan-Caruana Agreed. Adding a description to the otp tokens is coming in the next release.
