### ISSUE TITLE
OTP Tokens are generated using outdated sha1 algorythm

### ISSUE THREAD

**Issue by zem** [ubccr/mokey#99]
Is there a particular reason that OTP tokens are generated using sha1 rather than sha256 or sha512? 

https://github.com/ubccr/mokey/blob/56aba60d5580a88d4399b41b97dc80f33adcd040/server/otp.go#L172

As sha1 is considered insecure as a hash algorythm, I would suggest to go for sha256.

**Comment by aebruno** [comment]
Agreed, we should probably update this. The reason for using sha1 was that it seems to be the [default in FreeIPA](https://pagure.io/freeipa/blob/master/f/ipaserver/plugins/otptoken.py#_231) and in our testing it was supported by most mobile OTP client applications.

**Comment by Jonathan-Caruana** [comment]
Hello @aebruno 

Do you know if it's still in the pipes to change the default algorythm at least to sha256? (Of course having the choice between sha1/sha256/sha512 could be cool)

Regards,

**Comment by Jonathan-Caruana** [comment]
@aebruno Glad to read  ! 

I will be attentive for the next version.

Thank you for your quick reply and for your work.

Regards,
